{{- if eq (.Values.global.openshift | toString) "true" }}

allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
apiVersion: security.openshift.io/v1
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  name: scc-spire-csi-driver
readOnlyRootFilesystem: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:spire-system:spire-spiffe-csi-driver
volumes:
- configmap
- hostPath
- secret

{{ end }}
