apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: scc-spire-agent
priority: null
readOnlyRootFilesystem: true
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:spire-system:spire-agent
fsGroup:
  type: RunAsAny
groups: []
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
volumes:
  - configMap
  - hostPath
  - projected
  - secret
