global:
  openshift: true
  telemetry:
    prometheus:
      enabled: true

spire-server:
  nodeAttestor:
    k8sPsat:
      serviceAccountAllowList: ["spire-system:spire-agent"]
  notifier:
    k8sbundle:
      namespace: spire-system
  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null

  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: "passthrough"
    hosts:
      - host: spire-server.apps.tgeer-test.devcluster.openshift.com
        paths:
          - path: ''
            pathType: ImplementationSpecific


spire-agent:
  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null

upstream-spire-agent:
  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null

spiffe-oidc-discovery-provider:
  jwtIssuer: oidc-discovery.apps.tgeer-test.devcluster.openshift.com

  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null
  securityContext:
    allowPrivilegeEscalation: true
    runAsNonRoot: false
    privileged: true
  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: "edge"
    hosts:
      - host: oidc-discovery.apps.tgeer-test.devcluster.openshift.com
        paths:
          - path: /
            pathType: Prefix

tornjak-frontend:
  apiServerURL: https://spire-tornjak-backend.apps.tgeer-test.devcluster.openshift.com/
