global:
  openshift: true
  spire:
    jwtIssuer: oidc-discovery.$APP_SUBDOMAIN
  telemetry:
    prometheus:
      enabled: true

spire-server:
  tornjak:
    image:
      registry: quay.io
      repository: ablock/spiffe/tornjak-backend
      tag: v1.4.1
  nodeAttestor:
    k8sPsat:
      serviceAccountAllowList: ["spire-system:spire-agent"]
  notifier:
    k8sbundle:
      namespace: spire-system
  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null

  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: "passthrough"
    hosts:
      - host: spire-server.$APP_SUBDOMAIN
        paths:
          - path: ''
            pathType: ImplementationSpecific


spire-agent:
  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null

upstream-spire-agent:
  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null

spiffe-oidc-discovery-provider:

  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null
  securityContext:
    allowPrivilegeEscalation: true
    runAsNonRoot: false
    privileged: true
  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: "edge"
    hosts:
      - host: oidc-discovery.$APP_SUBDOMAIN
        paths:
          - path: /
            pathType: Prefix

tornjak-frontend:
  apiServerURL: https://spire-tornjak-backend.$APP_SUBDOMAIN/
  workingDir: /opt/app-root/src
  image:
    registry: quay.io
    repository: ablock/spiffe/tornjak-frontend
    tag: v1.4.1
  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null
